# TCL File Generated by Component Editor 11.1sp1
# Wed Feb 01 14:01:35 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | binary_vga_controller "Binary_VGA_Controller" v1.0.2
# | null 2012.02.01.14:01:35
# | 
# | 
# | D:/Project/DE2/test/DE2_NIOS_DEVICE_LED/HW/ip/Binary_VGA_Controller/hdl/VGA_NIOS_CTRL.v
# | 
# |    ./hdl/Img_DATA.hex syn, sim
# |    ./hdl/VGA_Param.h syn, sim
# |    ./hdl/Img_RAM.v syn, sim
# |    ./hdl/VGA_Controller.v syn, sim
# |    ./hdl/VGA_NIOS_CTRL.v syn, sim
# |    ./hdl/VGA_OSD_RAM.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module binary_vga_controller
# | 
set_module_property NAME binary_vga_controller
set_module_property VERSION 1.0.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME Binary_VGA_Controller
set_module_property TOP_LEVEL_HDL_FILE hdl/VGA_NIOS_CTRL.v
set_module_property TOP_LEVEL_HDL_MODULE VGA_NIOS_CTRL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME VGA_NIOS_CTRL
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/Img_DATA.hex {SYNTHESIS SIMULATION}
add_file hdl/VGA_Param.h {SYNTHESIS SIMULATION}
add_file hdl/Img_RAM.v {SYNTHESIS SIMULATION}
add_file hdl/VGA_Controller.v {SYNTHESIS SIMULATION}
add_file hdl/VGA_NIOS_CTRL.v {SYNTHESIS SIMULATION}
add_file hdl/VGA_OSD_RAM.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter RAM_SIZE INTEGER 307200 ""
set_parameter_property RAM_SIZE DEFAULT_VALUE 307200
set_parameter_property RAM_SIZE DISPLAY_NAME RAM_SIZE
set_parameter_property RAM_SIZE TYPE INTEGER
set_parameter_property RAM_SIZE UNITS None
set_parameter_property RAM_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_SIZE DESCRIPTION ""
set_parameter_property RAM_SIZE AFFECTS_GENERATION false
set_parameter_property RAM_SIZE HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_export
# | 
add_interface avalon_slave_0_export conduit end

set_interface_property avalon_slave_0_export ENABLED true

add_interface_port avalon_slave_0_export VGA_R export Output 10
add_interface_port avalon_slave_0_export VGA_G export Output 10
add_interface_port avalon_slave_0_export VGA_B export Output 10
add_interface_port avalon_slave_0_export VGA_HS export Output 1
add_interface_port avalon_slave_0_export VGA_VS export Output 1
add_interface_port avalon_slave_0_export VGA_SYNC export Output 1
add_interface_port avalon_slave_0_export VGA_BLANK export Output 1
add_interface_port avalon_slave_0_export VGA_CLK export Output 1
add_interface_port avalon_slave_0_export iCLK_25 export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk
set_interface_property avalon_slave_0 associatedReset reset_n
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 524288
set_interface_property avalon_slave_0 holdTime 1
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 1
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 oDATA readdata Output 16
add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 iADDR address Input 19
add_interface_port avalon_slave_0 iWR write Input 1
add_interface_port avalon_slave_0 iRD read Input 1
add_interface_port avalon_slave_0 iCS chipselect Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_n
# | 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT

set_interface_property reset_n ENABLED true

add_interface_port reset_n iRST_N reset_n Input 1
# | 
# +-----------------------------------
