# TCL File Generated by Component Editor 11.1sp1
# Wed Feb 01 14:02:36 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | seg7_lut_8 "SEG7_LUT_8" v1.0.1
# | null 2012.02.01.14:02:36
# | 
# | 
# | D:/Project/DE2/test/DE2_NIOS_DEVICE_LED/HW/ip/SEG7_LUT_8/hdl/SEG7_LUT_8.v
# | 
# |    ./hdl/SEG7_LUT.v syn, sim
# |    ./hdl/SEG7_LUT_8.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module seg7_lut_8
# | 
set_module_property NAME seg7_lut_8
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME SEG7_LUT_8
set_module_property TOP_LEVEL_HDL_FILE hdl/SEG7_LUT_8.v
set_module_property TOP_LEVEL_HDL_MODULE SEG7_LUT_8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME SEG7_LUT_8
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/SEG7_LUT.v {SYNTHESIS SIMULATION}
add_file hdl/SEG7_LUT_8.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset reset_n
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave iWR write Input 1
add_interface_port avalon_slave iDIG writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end oSEG0 export Output 7
add_interface_port conduit_end oSEG1 export Output 7
add_interface_port conduit_end oSEG2 export Output 7
add_interface_port conduit_end oSEG3 export Output 7
add_interface_port conduit_end oSEG4 export Output 7
add_interface_port conduit_end oSEG5 export Output 7
add_interface_port conduit_end oSEG6 export Output 7
add_interface_port conduit_end oSEG7 export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_n
# | 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT

set_interface_property reset_n ENABLED true

add_interface_port reset_n iRST_N reset_n Input 1
# | 
# +-----------------------------------
