# TCL File Generated by Component Editor 11.1sp1
# Wed Feb 01 14:02:02 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dm9000a "DM9000A" v1.0.2
# | null 2012.02.01.14:02:02
# | 
# | 
# | D:/Project/DE2/test/DE2_NIOS_DEVICE_LED/HW/ip/DM9000A/hdl/DM9000A_IF.v
# | 
# |    ./hdl/DM9000A_IF.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module dm9000a
# | 
set_module_property NAME dm9000a
set_module_property VERSION 1.0.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME DM9000A
set_module_property TOP_LEVEL_HDL_FILE hdl/DM9000A_IF.v
set_module_property TOP_LEVEL_HDL_MODULE DM9000A_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME DM9000A_IF
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/DM9000A_IF.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_export
# | 
add_interface avalon_slave_0_export conduit end

set_interface_property avalon_slave_0_export ENABLED true

add_interface_port avalon_slave_0_export iOSC_50 export Input 1
add_interface_port avalon_slave_0_export ENET_DATA export Bidir 16
add_interface_port avalon_slave_0_export ENET_CMD export Output 1
add_interface_port avalon_slave_0_export ENET_RD_N export Output 1
add_interface_port avalon_slave_0_export ENET_WR_N export Output 1
add_interface_port avalon_slave_0_export ENET_CS_N export Output 1
add_interface_port avalon_slave_0_export ENET_RST_N export Output 1
add_interface_port avalon_slave_0_export ENET_CLK export Output 1
add_interface_port avalon_slave_0_export ENET_INT export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk
set_interface_property avalon_slave_0 associatedReset reset_n
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 2
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 40
set_interface_property avalon_slave_0 readWaitTime 40
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 writeWaitStates 40
set_interface_property avalon_slave_0 writeWaitTime 40

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 iCMD address Input 1
add_interface_port avalon_slave_0 iRD_N read_n Input 1
add_interface_port avalon_slave_0 iWR_N write_n Input 1
add_interface_port avalon_slave_0 iCS_N chipselect_n Input 1
add_interface_port avalon_slave_0 oDATA readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0_irq
# | 
add_interface avalon_slave_0_irq interrupt end
set_interface_property avalon_slave_0_irq associatedAddressablePoint avalon_slave_0
set_interface_property avalon_slave_0_irq associatedClock clk
set_interface_property avalon_slave_0_irq associatedReset clk_reset

set_interface_property avalon_slave_0_irq ENABLED true

add_interface_port avalon_slave_0_irq oINT irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_n
# | 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT

set_interface_property reset_n ENABLED true

add_interface_port reset_n iRST_N reset_n Input 1
# | 
# +-----------------------------------
